name: publication

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker build & push backend image
        run: |
          docker build ./backend -t akimovve/docker-compose-app:backend-0.0.1
          docker push akimovve/docker-compose-app:backend-0.0.1
          
      - name: Docker build & push frontend image
        run: |
          docker build ./frontend -t akimovve/docker-compose-app:frontend-0.0.1
          docker push akimovve/docker-compose-app:frontend-0.0.1
